export default {
  TOGGLE_SUBMIT: 'TOGGLE_SUBMIT',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOGIN_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_FAILURE: 'REGISTER_FAILURE'
}
